- https://www.youtube.com/watch?v=FsroWpkUuYI&list=PLjwX9KFWtvNnOc4HtsvaDf1XYG3O5bv5s An excellent YT playlist where each vid is under 5 mins
- https://youtube.com/playlist?list=PL_iP0SGUzx9SvI_loo4I6orC-6o5-7hKp For a more in-depth understanding of ACF and PACF
- The classic book Forecasting: Principles and Practice https://otexts.com/fpp3/index.html
